### PR TITLE
Fix: Support for React v17

### PR DESCRIPTION
**Pull request by mrfambo**

### CODE REVIEW

**Review by mladimatija — APPROVED** [review]

**Review by nicotroia — APPROVED** [review]

**Comment by nicotroia** [comment]
@roylee0704 have a minute to look this over? Thank you

**Comment by roylee0704** [comment]
> @roylee0704 have a minute to look this over? Thank you

LGTM, merged. Thanks for the PR!

**Comment by tehbi4** [comment]
@roylee0704, hello. Could you please publish version with this changes?

**Comment by aganoza** [comment]
@roylee0704 please, could this be published in npm registry?

It's causing problems with >=npm@7

Found: react@17.0.2
node_modules/react
  react@"^17.0.1" from the root project

Could not resolve dependency:
**peer react@"^0.14.3 || ^15.5.4 || ^16.0.0" from react-flexbox-grid@2.1.2**
node_modules/react-flexbox-grid
  react-flexbox-grid@"^2.1.2" from the root project

In the meantime i'm using npm install --force

**Pull request merged**
