### PR TITLE
Add TypeScript definitions support #62.

### PR DESCRIPTION
**Pull request by IRus**
Hi, @roylee0704 

Since i, and other user of your great project uses TypeScript, i added definition for your project.
Hope will be merged and released patch version soon :+1:

### CODE REVIEW

**Comment by IRus** [comment]
Hi @roylee0704! Any concerns about this PR?

**Comment by roylee0704** [comment]
Nope @Irus,  LGTM. :) Apologize that i only notice now.

**Comment by roylee0704** [comment]
I will merge and release once I have access to my laptop :) thanks for the PR!

**Comment by IRus** [comment]
What's up :)

**Comment by beckend** [comment]
Can you fix the typings according to [issue](https://github.com/roylee0704/react-flexbox-grid/issues/22)

**Comment by IRus** [comment]
@beckend sure

**Comment by IRus** [comment]
@beckend @roylee0704 Done https://github.com/IRus/react-flexbox-grid/commit/16d41ee134d22e373f5e0abbd402cbde1e76b144

**Comment by beckend** [comment]
Looks good, wait for maintainer to merge.

**Comment by maxcan** [comment]
@roylee0704 are you open to this PR?  If so I'll work on cleaning up the dependencies

**Comment by silvenon** [comment]
@IRus I don't know TypeScript, but I see no reason not to merge this if you can confirm that this PR is complete considering the latest changes.

**Comment by IRus** [comment]
@silvenon cheking

**Comment by IRus** [comment]
@silvenon renamed types according latest changes. Props looks good.

**Comment by cyberhck** [comment]
Thanks for the TypeDefinition, I noticed you added tests, but I'm not sure if they're even being run, can you weigh in here? :slightly_smiling_face:

**Comment by IRus** [comment]
@cyberhck Nice question! No, they didn't. On CI at least. But locally you can try to compile or open in webstorm/vscode to check that definitions works properly.

**Pull request merged**
