### PR TITLE
Use evgenyrodionov/flexboxgrid2 instead of roylee0704/react-flexbox-grid

### PR DESCRIPTION
**Pull request by Kamahl19**
Code for #137 
It also allows #82 since flexboxgrid2 includes .hidden- classes
It also solves #57

### CODE REVIEW

**Comment by DanielRamosAcosta** [comment]
Please merge this!

**Comment by evgenyrodionov** [comment]
Note: it will be breaking change because [we updated breakpoints](https://github.com/evgenyrodionov/flexboxgrid2#breakpoints) to match Bootstrap 4.

**Comment by musicalshore** [comment]
It's not a breaking change if it's already broken.

**Comment by danny-andrews** [comment]
> It's not a breaking change if it's already broken.

@musicalshore What's already broken?

**Comment by roylee0704** [comment]
Thanks for the PR! @Kamahl19

**Pull request merged**
