### PR TITLE
Build dist version (fixes #129)

### LINKED ISSUE #129: Style is not being imported after v1.1.4
After the last release `v1.1.4`, on my project, the grid stopped to work. It looks like the classnames are different and don't contain any stylesheet for it. You can help me on this, please?
image

### PR DESCRIPTION
**Pull request by danny-andrews**
Changing functionality added in #126 to be backwards-compatible. If you want to use the pre-built css version, import from `react-flexbox-grid/isomorphic`.

### CODE REVIEW

**Comment by roylee0704** [comment]
Thanks bro @danny-andrews ! Sorry for the delay.

**Comment by roylee0704** [comment]
@danny-andrews It seems to fail my test cases. Any ideas?

**Comment by roylee0704** [comment]
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/style-loader!./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader!./~/flexboxgrid/dist/flexboxgrid.css
/Users/roylee/dev/react-flexbox-grid/node_modules/style-loader/index.js!/Users/roylee/dev/react-flexbox-grid/node_modules/css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!/Users/roylee/dev/react-flexbox-grid/node_modules/postcss-loader/index.js!/Users/roylee/dev/react-flexbox-grid/node_modules/sass-loader/index.js!/Users/roylee/dev/react-flexbox-grid/node_modules/flexboxgrid/dist/flexboxgrid.css:5:1: Unknown word  3 | // load the styles
  4 | var content = require("!!./../../css-loader/index.js?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./../../postcss-loader/index.js!./../../sass-loader/index.js!./flexboxgrid.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!./../../style-loader/addStyles.js")(content, {});

ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/style-loader!./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader!./~/flexboxgrid/dist/flexboxgrid.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (/Users/roylee/dev/react-flexbox-grid/node_modules/postcss/lib/input.js:51:23)
    at parse (/Users/roylee/dev/react-flexbox-grid/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (/Users/roylee/dev/react-flexbox-grid/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (/Users/roylee/dev/react-flexbox-grid/node_modules/postcss/lib/processor.js:117:12)
    at processCss (/Users/roylee/dev/react-flexbox-grid/node_modules/css-loader/lib/processCss.js:171:11)
    at Object.module.exports (/Users/roylee/dev/react-flexbox-grid/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/flexboxgrid/dist/flexboxgrid.css 4:14-369

**Comment by danny-andrews** [comment]
@roylee0704 https://github.com/roylee0704/react-flexbox-grid/pull/133

**Pull request merged**
