### PR TITLE
Remove classnames and babel-polyfill peerDependency

### LINKED ISSUE #49: Remove classnames dependency
I would love to see the `classnames` dependency removed. In general, it seems to me to be best practice to try to encapsulate the dependencies for a given project within the project itself and not to force package users to reproduce your development setup and to use the styling tools you've chosen.  I love this package and what you've done here and think that the structure is really great, but we take great pains not to include packages and build configuration that don't actually apply to our own code - it adds confusion for new developers and it makes it far more difficult to uninstall single dependencies.  Any chance you're planning to or would consider planning to get rid of this dependency?

### LINKED ISSUE #51: Can we remove `babel-polyfill` dependency?
Hey guys, I was wondering which parts of the code depend on `babel-polyfill`?

Very similar to https://github.com/roylee0704/react-flexbox-grid/issues/49 request.
I would very much like not to include `babel-polyfill` in my project, since I don't need it.

I'm willing to help out, just let me know where are we using something that `babel-polyfill` covers?

### PR DESCRIPTION
**Pull request by Nathan-Schwartz**
Resolves #49 
Resolves #51 

Wrote a small local utility to replace classnames.

Took out babel-polyfill as well. It is still a devDependency so mocha and webpack still work fine 👍

### CODE REVIEW

**Comment by Nathan-Schwartz** [comment]
I'm not sure what you want to do about `highlight-loader`. It was pre-existing but it seems VersionEye doesn't like it. @roylee0704

**Comment by roylee0704** [comment]
Sure i will check it out later :)

**Comment by Nathan-Schwartz** [comment]
@roylee0704 When do you think you will be able to review the pull requests being made? It has been over 3 months.

**Comment by silvenon** [comment]
@Nathan-Schwartz thanks so much for the contribution! I'm so sorry that this PR was sitting here for such a long time. 😓 We already merged #66, which contained similar changes.

**Pull request closed without merging**
