### PR TITLE
stateless components

### PR DESCRIPTION
**Pull request by heldr**
#36

### CODE REVIEW

**Comment by silvenon** [comment]
Now that you switched to shallow rendering, is jsdom in `test/setup.js` still needed?

**Comment by silvenon** [comment]
Also, to make tests more readable I would use [Enzyme](http://airbnb.io/enzyme/), but maybe that's an overkill for such a small library.

Otherwise LGTM 👍

**Comment by heldr** [comment]
We might also remove karma too, since shallow rendering runs on node

**Comment by roylee0704** [comment]
Great work here!

**Pull request merged**
